{{- if .Values.backendIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.backendIngress.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "{{ .Values.backendIngress.annotations.rewriteTarget }}"
    nginx.ingress.kubernetes.io/cors-allow-origin: "{{ .Values.backendIngress.annotations.corsAllowOrigin }}"
    nginx.ingress.kubernetes.io/cors-allow-methods: "{{ .Values.backendIngress.annotations.corsAllowMethods }}"
    nginx.ingress.kubernetes.io/cors-allow-headers: "{{ .Values.backendIngress.annotations.corsAllowHeaders }}"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "{{ .Values.backendIngress.annotations.corsAllowCredentials }}"
spec:
  ingressClassName: {{ .Values.backendIngress.ingressClassName }}
  tls:
    - hosts:
        - {{ .Values.backendIngress.host }}
      secretName: {{ .Values.backendIngress.tlsSecretName }}
  rules:
    - host: {{ .Values.backendIngress.host }}
      http:
        paths:
          - path: {{ .Values.backendIngress.path }}
            pathType: {{ .Values.backendIngress.pathType }}
            backend:
              service:
                name: {{ .Values.backendIngress.serviceName }}
                port:
                  number: {{ .Values.backendIngress.servicePort }}
{{- end }}