apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mydatasourceConfig.name }}
  namespace: {{ .Values.namespace }}
data:
  application.properties: |
    {{- .Values.mydatasourceConfig.properties | nindent 4  }}
