# jwt-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jwtSecret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.jwtSecret.value | quote }}
