apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: yuval-skillup
spec:
  containers:
  - name: debug-container
    image: bitnami/kubectl:latest
    command: ["/bin/sh"]
    tty: true
    stdin: true
  restartPolicy: Never
